---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: hugo/content/404
  label: '404'
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content/career
  label: Career
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content/case-studies
  label: Case studies
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content/contact
  label: Contact
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content/homepage
  label: Homepage
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
  templates:
  - default
upload_dir: hugo/static
public_path: hugo/static
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - HUGO_ENV=dev
  - HUGO_VERSION=0.54.0
  preview_output_directory: dist
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --source hugo/ --port 8080 --bind
    0.0.0.0 --renderToDisk -d public
version: 0.54.0
